angular.module("YTPlaylistManager",["ngMaterial","ngMdIcons"]);

angular.module("YTPlaylistManager").config(["$mdThemingProvider",function(e){e.theme("default").primaryPalette("light-blue").accentPalette("red",{"default":"900"})}]);

angular.module("YTPlaylistManager").constant("$config",{API_KEY:"AIzaSyDJIOlGzyjPFEQ5j-Q2qEJVbOJtgqmby_Y",CLIENT_ID:"877549163404-chjiknp3ffeiatmb2mcb8dfp23u7sm8q.apps.googleusercontent.com",SCOPE:"https://www.googleapis.com/auth/youtube"});

angular.module("YTPlaylistManager").run(["$rootScope","YTResourceProvider","channel","$config",function(e,o,a,r){$(window).load(function(){var r;if(e.$broadcast("pageLoaded"),localStorage.options)try{r=JSON.parse(localStorage.options)}catch(n){console.error(n)}r?a.options=r:r=a.options,r.autologin?o.login().then(function(o){var r=o.result.items[0];a.basicInfo={authorized:!0,userId:r.id,username:r.snippet.title,profilePic:r.snippet.thumbnails["default"].url,bgPic:r.brandingSettings.image.bannerMobileImageUrl},e.$broadcast("loggedIn"),$(".preloader-wrapper").fadeOut()}):$(".preloader-wrapper").fadeOut()})}]);

angular.module("YTPlaylistManager").controller("aboutModalCtrl",["$scope","$mdDialog",function(l,o){l.hide=function(){o.hide()}}]);

angular.module("YTPlaylistManager").controller("mainCtrl",["$scope","channel",function(n,o){n.$on("loggedIn",function(){n.info=o.basicInfo,n.options=o.options})}]);

angular.module("YTPlaylistManager").controller("playerCtrl",["$rootScope","$scope","$interval","channel",function(e,o,i,t){function a(){if(t.authorized&&t.options.quality)return t.options.quality;var e=screen.width;return e>=1920?"hd1080":1920>e&&e>=1280?"hd720":1280>e&&e>=854?"large":854>e&&e>=640?"medium":640>e?"small":void 0}function l(e){o.playStatusIcon=1===e.data?"pause":"play_arrow",o.currentVideoDuration=o.player.getDuration(),o.playerState=e.data,o.$apply()}function n(e){o.volumeStatusIcon=0===e?"volume_off":e>0&&33>=e?"volume_mute":e>33&&66>=e?"volume_down":"volume_up"}function u(e){o.currentVideoDuration=o.player.getDuration(),o.playerVolume=o.player.getVolume(),e.target.setPlaybackQuality(o.videoQuality),t.basicInfo.authorized||(t.activePlaylist=t.mockPlaylist,o.currentVideo=t.activePlaylist.videos[t.activeVideoIndex])}function r(){o.currentVideo=t.activePlaylist.videos[t.activeVideoIndex],o.player.loadVideoById({videoId:o.currentVideo.id,suggestedQuality:o.videoQuality})}o.playStatusIcon="play_arrow",o.volumeStatusIcon="volume_up",o.playPosition="0%",o.playerVolume=100,o.previousVolume=100,o.playerState=-1,o.activePlaylist=t.activePlaylist,o.activeVideoindex=t.activeVideoindex,o.videoQuality=a(),o.playPauseVideo=function(){1===o.playerState?o.player.pauseVideo():o.player.playVideo()},o.stopVideo=function(){o.player.seekTo(0),o.player.stopVideo()},o.muteVideo=function(){var e=0!==o.playerVolume?0:o.previousVolume;o.previousVolume=o.playerVolume,o.playerVolume=e,o.player.setVolume(e),n(e)},o.adjustVolume=function(){o.player.setVolume(o.playerVolume),n(o.playerVolume)},o.init=function(){o.player=new YT.Player("player",{height:"100%",width:"100%",suggestedQuality:o.videoQuality,videoId:t.mockPlaylist.videos[t.activeVideoIndex].id,playerVars:{controls:0,disablekb:1,modestbranding:1,rel:0,showinfo:0,iv_load_policy:3},events:{onStateChange:l,onReady:u}})},o.changePlayingPosition=function(e){var i=$(".video-progress").offset().left,t=(100*(e.clientX-i)/229).toFixed(4),a=(o.currentVideoDuration*t/100).toFixed(2);o.playPosition=t+"%",o.player.seekTo(a)},o.previousVideo=function(){t.activeVideoIndex--,t.activeVideoIndex<0&&(t.activeVideoIndex=t.activePlaylist.videos.length-1),r()},o.nextVideo=function(){t.activeVideoIndex++,t.activeVideoIndex>=t.activePlaylist.videos.length&&(t.activeVideoIndex=0),r()},i(function(){1===o.playerState&&(o.playPosition=100*o.player.getCurrentTime()/o.currentVideoDuration+"%")},500),o.$on("pageLoaded",o.init),o.$on("loggedIn",function(){t.options.autoplay&&o.player.playVideo()})}]);

angular.module("YTPlaylistManager").controller("playlistCtrl",["$q","$scope","$rootScope","$interval","$timeout","YTResourceProvider","channel",function(e,t,n,l,s,a,i){t.playlists=[i.mockPlaylist],t.togglePlaylist=function(e,n){var l=angular.element(e.currentTarget.parentNode.parentNode),a=angular.element(document.querySelector(".playlist.opened"));l.hasClass("opened")||(a.length?(t.closePlaylist(a),s(function(){t.openPlaylist(l)},500)):t.openPlaylist(l)),i.playlists[n]&&!i.playlists[n].videos&&t.getPlaylistItems(i.playlists[n])},t.openPlaylist=function(e){var t;t=e.currentTarget?angular.element(e.currentTarget.parentNode.parentNode):e,n.openedPlaylist=!0,t.addClass("opening"),s(function(){t.removeClass("opening").addClass("opened")},500)},t.closePlaylist=function(e){var t;t=e.currentTarget?angular.element(e.currentTarget.parentNode.parentNode):e,t.addClass("closing"),n.openedPlaylist=!1,s(function(){t.removeClass("opened"),s(function(){t.removeClass("closing")},1e3)},500)},t.getPlaylists=function(){console.log("fetching");var e={channelId:i.basicInfo.userId,part:"snippet,contentDetails,status",pageToken:i.nextPlaylistsToken,maxResults:8};a.sendRequest("playlists.list",e).then(function(e){i.nextPlaylistsToken=e.nextPageToken,i.playlists=i.playlists.concat(e.result.items),t.playlists=i.playlists})},t.getPlaylistItems=function(n){var l={playlistId:n.id,part:"id,snippet",maxResults:50,pageToken:n.nextPageToken||null};a.sendRequest("playlistItems.list",l).then(function(e){return n.videos||(n.videos=[]),n.itemCount=e.result.pageInfo.totalResults,e.result.items}).then(function(l){var s=[];l.forEach(function(e,n){var l=t.getPlaylistItemDetails(e.snippet.resourceId.videoId);s.push(l),e.playlistItemId=e.id}),e.all(s).then(function(e){n.videos=n.videos.concat(e)})})},t.getPlaylistItemDetails=function(t){var n=e.defer(),l={part:"contentDetails,snippet,statistics",id:t};return a.sendRequest("videos.list",l).then(function(e){n.resolve(e.result.items[0])},function(e){n.reject(e)}),n},t.$on("loggedIn",t.getPlaylists)}]);

angular.module("YTPlaylistManager").controller("sidebarCtrl",["$rootScope","$scope","channel","YTResourceProvider","$mdToast","$mdSidenav","$mdDialog",function(e,t,n,o,i,s,a){t.settingsIcon="expand_more",t.settingsOpened=!1,t.login=function(){o.login().then(function(o){var i=o.result.items[0];n.basicInfo={authorized:!0,userId:i.id,username:i.snippet.title,profilePic:i.snippet.thumbnails["default"].url,bgPic:i.brandingSettings.image.bannerMobileImageUrl},t.info=n.basicInfo,e.$broadcast("loggedIn")},function(e){i.show(i.simple().content(e.error.code+" "+e.error.message).highlightAction(!1).position({top:!0,right:!0}))})},t.toggleSidenav=function(){s("sidenav").toggle()},t.showAbout=function(e){a.show({controller:"aboutModalCtrl",templateUrl:"assets/templates/about.modal.html",parent:angular.element(document.body),targetEvent:e.target})},t.toggleSettings=function(){t.settingsIcon="expand_more"===t.settingsIcon?"expand_less":"expand_more",t.settingsOpened=!t.settingsOpened},t.saveSettings=function(){localStorage.options=JSON.stringify(t.options)}}]);

angular.module("YTPlaylistManager").directive("draggableElem",["$document",function(t){return{restrict:"A",replace:!1,link:function(e,r,l){function n(t){a.css({left:t.clientX-10,top:t.clientY-10,bottom:"auto",right:"auto"})}function o(e){t.off("mousemove",n),t.off("mouseup",o)}var a=$(l.draggableElem);r.on("mousedown",function(e){e.preventDefault(),t.on("mousemove",n),t.on("mouseup",o)})}}}]).directive("mainSidebar",function(){return{restrict:"E",replace:!0,templateUrl:"assets/templates/sidebar.html",controller:"sidebarCtrl"}}).directive("controlPanel",function(){return{restrict:"E",replace:!0,templateUrl:"assets/templates/control.panel.html",controller:"playerCtrl"}}).directive("playlist",function(){return{restrict:"E",replace:!0,templateUrl:"assets/templates/playlist.html",controller:"playlistCtrl"}}).directive("lock",function(){return{restrict:"A",replace:!1,link:function(t,e,r){e.find("input, textarea");e.attr("readonly",!0),$(e).on("focus",function(){e.attr("readonly",!1)}),$(e).on("blur",function(){e.attr("readonly",!0)})}}});

angular.module("YTPlaylistManager").service("YTResourceProvider",["$q","$config","$rootScope",function(e,r,i){var n={};return n.login=function(){var i=e.defer();return gapi.client.setApiKey=r.API_KEY,gapi.auth.authorize({client_id:r.CLIENT_ID,scope:r.SCOPE,immediate:!1},function(){gapi.client.load("youtube","v3",function(){var e=gapi.client.youtube.channels.list({mine:!0,part:"id, snippet, brandingSettings"});e.execute(function(e){e.error?i.reject(e):i.resolve(e)})})}),i.promise},n.sendRequest=function(r,i){var n=e.defer();r=r.split(".");var t=gapi.client.youtube[r[0]][r[1]](i);return t.execute(function(e){e.error?(console.error({operationType:r,operationParams:i,error:e.error}),n.reject()):n.resolve(e)}),n.promise},n}]);

angular.module("YTPlaylistManager").service("channel",function(){var i={basicInfo:{authorized:!1},options:{autologin:!1,autoplay:!1,videoQuality:"hd720"},activePlaylist:null,activeVideoIndex:1,playlists:[],mockPlaylist:{itemCount:7,snippet:{title:"Hello there!",description:"This is just hardcoded sample playlist. To fully enjoy this application login with your YouTube account.",thumbnails:{high:{url:"assets/img/noth.png"}}},videos:[{id:"o3mP3mJDL2k",snippet:{title:"Shakira - Can't Remember to Forget You ft. Rihanna",thumbnails:{"default":{url:"//i.ytimg.com/vi/o3mP3mJDL2k/mqdefault.jpg"}}}},{id:"tuMgJrFoAFY",snippet:{title:"Ten Walls - Walking With Elephants [Official Video]",thumbnails:{"default":{url:"//i.ytimg.com/vi/tuMgJrFoAFY/mqdefault.jpg"}}}},{id:"ESXgJ9-H-2U",snippet:{title:"Kiesza - Hideaway (Official Video)",thumbnails:{"default":{url:"//i.ytimg.com/vi/ESXgJ9-H-2U/mqdefault.jpg"}}}},{id:"SYM-RJwSGQ8",snippet:{title:"Tove Lo - Habits (Stay High) - Hippie Sabotage Remix",thumbnails:{"default":{url:"//i.ytimg.com/vi/SYM-RJwSGQ8/mqdefault.jpg"}}}},{id:"81EdENK_9qQ",snippet:{title:"SPADA & ELEN LEVON - Cool Enough (Official Video)",thumbnails:{"default":{url:"//i.ytimg.com/vi/81EdENK_9qQ/mqdefault.jpg"}}}},{id:"L8eRzOYhLuw",snippet:{title:"Ariana Grande - Break Free ft. Zedd",thumbnails:{"default":{url:"//i.ytimg.com/vi/L8eRzOYhLuw/mqdefault.jpg"}}}},{id:"gCYcHz2k5x0",snippet:{title:"Martin Garrix - Animals (Official Video)",thumbnails:{"default":{url:"//i.ytimg.com/vi/gCYcHz2k5x0/mqdefault.jpg"}}}}]}};return i});

//# sourceMappingURL=app.js.map